<?php
/**
 * @title MPGHP · Génies en herbe et Pantologie
 * @section accueil
 * @abstract Quatre joueurs, un buzzer et toutes les questions du monde. Découvrez Génies en herbe et trouvez votre ligue.
 */
?>
<section class="masthead wrap"><p class="eyebrow">Le jeu-questionnaire qui nous rassemble</p><h1>Génies en herbe<span class="masthead-star" aria-hidden="true">✳</span></h1><div class="masthead-line"><p><em>L’œil de la connaissance ouvert sur le monde</em></p><p>Mouvement provincial Génies en herbe / Pantologie</p></div></section>
<section class="editorial-hero wrap"><div class="editorial-intro"><p class="eyebrow">Curieux de nature. Joueurs d’équipe.</p><h2>Quatre joueurs, <br>un buzzer et <span>toutes les questions</span> du monde.</h2><p class="lead">À l’école ou entre passionnés, on répond vite, on apprend beaucoup et on joue ensemble. Bienvenue dans le mouvement Génies en herbe / Pantologie.</p><div class="actions"><a class="button" href="<?= h($relroot) ?>decouvrir/">Découvrir le jeu ↗</a><a class="button button-outline" href="<?= h($relroot) ?>ligues/">Trouver ma ligue →</a></div></div><div class="demo-quiz" id="demo-quiz"><div class="quiz-heading"><p class="eyebrow">À vous de jouer</p><span>Sciences · Démonstration</span></div><span class="quiz-number" aria-hidden="true">?</span><h2 id="quiz-question">Quel est le symbole chimique de l’or?</h2><p class="quiz-instruction">Une question. Quatre réponses. Faites votre choix.</p><div class="quiz-options" role="group" aria-labelledby="quiz-question"><button type="button" data-answer="Or"><span>A</span> Or</button><button type="button" data-answer="Ag"><span>B</span> Ag</button><button type="button" data-answer="Au"><span>C</span> Au</button><button type="button" data-answer="Go"><span>D</span> Go</button></div><p class="quiz-feedback" role="status" aria-live="polite">À votre tour!</p><button class="quiz-reset" type="button" hidden>Rejouer ↺</button><noscript><p>La réponse : Au. Son symbole vient du latin <em>aurum</em>.</p></noscript></div></section>
<section class="rounds wrap" aria-labelledby="rounds-title"><div class="rounds-intro"><p class="eyebrow">Le premier point, c’est de se lancer.</p><h2 id="rounds-title">Entrez dans le jeu.</h2></div><article class="round"><span class="round-number" aria-hidden="true">01</span><div><p class="eyebrow">Première manche</p><h3>Découvrir.</h3><p>Des équipes, un animateur, des questions sur tous les sujets. Les bases pour comprendre le jeu et prendre goût au prochain match.</p></div><a class="round-link" href="<?= h($relroot) ?>decouvrir/">C’est quoi, Génies en herbe? <span aria-hidden="true">↗</span></a></article><article class="round"><span class="round-number" aria-hidden="true">02</span><div><p class="eyebrow">Deuxième manche</p><h3>Trouver son équipe.</h3><p>Au primaire, au secondaire ou après les études : découvrez les ligues et le parcours qui vous ressemble.</p></div><a class="round-link" href="<?= h($relroot) ?>ligues/">Voir les ligues <span aria-hidden="true">↗</span></a></article><article class="round"><span class="round-number" aria-hidden="true">03</span><div><p class="eyebrow">Troisième manche</p><h3>S’entraîner.</h3><p>De l’histoire aux sciences, préparez votre équipe avec les guides et le service de commande de questionnaires.</p></div><a class="round-link" href="<?= h($relroot) ?>questionnaires/">Les questionnaires <span aria-hidden="true">↗</span></a></article><article class="round"><span class="round-number" aria-hidden="true">04</span><div><p class="eyebrow">À vous de jouer</p><h3>Faire le premier pas.</h3><p>Rassemblez un groupe curieux, trouvez un responsable et découvrez les possibilités de participation.</p></div><a class="round-link" href="<?= h($relroot) ?>commencer/">Démarrer une équipe <span aria-hidden="true">↗</span></a></article></section>
<section class="editorial-bottom wrap"><div><p class="eyebrow">Choisissez votre terrain de jeu</p><h2>Les ligues.</h2><ul class="league-rows"><?php foreach(donnees_site()['ligues'] as $ligue): if($ligue['slug']==='civile-b') continue; ?><li><a href="<?= h($relroot.'ligues/'.$ligue['slug'].'/') ?>"><strong><?= h($ligue['nom']) ?></strong><span><?= h($ligue['public']) ?></span><span aria-hidden="true">→</span></a></li><?php endforeach; ?></ul><a class="text-link" href="<?= h($relroot) ?>ligues/">Explorer tous les parcours →</a></div><div class="editorial-news"><p class="eyebrow">Le fil du Mouvement</p><h2>À suivre.</h2><article><p class="news-date">18 octobre 2025 · Archives</p><h3><a href="<?= h($relroot) ?>nouvelles/">Inscriptions au primaire : l’annonce de la saison 2025–2026.</a></h3><p>Retrouvez l’annonce historique. Pour participer aujourd’hui, consultez les responsables de votre ligue.</p></article><a class="text-link" href="<?= h($relroot) ?>calendrier/">Calendrier et résultats →</a><a class="text-link" href="<?= h($relroot) ?>ressources/">Guides et documents →</a></div></section>
<section class="closing-statement"><div class="wrap"><p class="eyebrow">Pas besoin de tout savoir pour jouer.</p><p>La connaissance <br>de <em>tout.</em> <br>En équipe.</p><a class="button" href="<?= h($relroot) ?>participer/">Entrer en jeu ↗</a></div></section>
